server:
  port: 8888

spring:
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_URL}
    service:
      name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CFG_URI}
          default-label: main
          skip-ssl-validation: true
          username: ${GIT_CFG_USER}
          password: ${GIT_JAVA6_KEY}