server:
  port: 9091
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/ProductDB
  jpa:
    hibernate:
      ddl-auto: update
authservice:
  bunu-ben-yazdim:
    secret-key: ${JAVA_SECRETKEY}
    issuer: ${JAVA6_ISSUER}