server:
  port: 9093
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/UserDB
  jpa:
    hibernate:
      ddl-auto: update
authservice:
  bunu-ben-yazdim:
    secret-key: ${JAVA_SECRETKEY}
    issuer: ${JAVA6_ISSUER}
user-service:
  redis:
    host: localhost
    port: 6379